<?
/**
 * 
 * This case study application uses codeignitor
 * CodeIgniter is a MVC PHP Framework
 * In the root dirctory is the frontend design code of the site. 
 * 
 * In the '_' folder are the application asset files which contain the
 * CSS and JS of the site. 
 *
 * In the application/ directory are the files of the application. 
 * The main folders to pay attention to are 'MODEL, VIEW AND CONTROLLER'
 * These will contain the files to the alumni directory, The admin section
 * the reports section of the site. 
 *
 * The models control the database interaction, the views handle the interface and the controller
 * handles everything in between. 
 *
 * - steve
 *
 * 
 */